### ISSUE TITLE
pypi package broken

### ISSUE THREAD

**Issue by ltalirz** [broeder-j/aiida-fleur#40]
```
pip install aiida-fleur
   Downloading https://files.pythonhosted.org/packages/f7/c7/4824f9f3a391f59658a258a0ba01265d81f54bca574f8af645e956bfe9c4/aiida-fleur-0.6.0.tar.gz (155kB)
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-FIzeJI/aiida-fleur/setup.py", line 9, in <module>
            with open('setup.json', 'r') as info:
        IOError: [Errno 2] No such file or directory: 'setup.json'
```

In order to fix this, please add a `MANIFEST.in` with content
```
include setup.json
```
see e.g. https://github.com/cp2k/aiida-cp2k/blob/master/MANIFEST.in

**Comment by ltalirz** [comment]
Just a heads-up that, until this is fixed, I'm forced to remove `aiida-fleur` from [`aiidalab`](https://pypi.org/project/aiidalab/)  (pypi does not allow for the processing of dependency links for direct install from git repos)

**Comment by broeder-j** [comment]
Please try the 0.6.2 release on PyPI. 
From what I have tested it should work, or install the 0.6.2 tag directly from the repo. 

If it works smoothly I will close this issue.
